version: "3.9"

services:
  backend:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - db

  db:
    image: postgres:15
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - ./pgdata:/var/lib/postgresql/data
