version: "3"

services:
  backend:
    build: .
    container_name: fitcheckme-backend
    ports:
      - 8080:8080
    depends_on:
      - fitcheckme-db

  fitcheckme-db:
    image: postgres:15
    container_name: fitcheckme-db
    ports:
      - 5433:5432
    env_file:
      - src/main/resources/.env
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db: